### ISSUE TITLE
Need add all FMSPC to the policy list for cross platform migration.

### ISSUE THREAD

**Issue by jyao1** [intel/MigTD#112]
related issue: https://github.com/intel/MigTD/issues/44

The production platform list:  `https://api.trustedservices.intel.com/sgx/certification/v4/fmspcs`, choose E5.
The pre-production platform list: `https://sbx.api.trustedservices.intel.com/sgx/certification/v4/fmspcs`, choose E5.

According to https://api.portal.trustedservices.intel.com/content/documentation.html#pcs-tcb-info-tdx-v4, 
we need to use below command:
`curl -v -X GET "https://api.trustedservices.intel.com/tdx/certification/v4/tcb?fmspc={}"` and 
`curl -v -X GET "https://sbx.api.trustedservices.intel.com/tdx/certification/v4/tcb?fmspc={}"`

**Comment by gaojiaqi7** [comment]
Closed by https://github.com/intel/MigTD/pull/113
