### ISSUE TITLE
Consider support tdxModuleIdentities with id `TDX_02` in policy

### ISSUE THREAD

**Issue by gaojiaqi7** [intel/MigTD#193]
For example:
```
https://sbx.api.trustedservices.intel.com/tdx/certification/v4/tcb?fmspc=20806F000000
```

There are two tdxModuleIdentities for fmspc `20806F000000`:
```
[{"id":"TDX_02","mrsigner":"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","attributes":"0000000000000000","attributesMask":"FFFFFFFFFFFFFFFF","tcbLevels":[{"tcb":{"isvsvn":0},"tcbDate":"2022-11-09T00:00:00Z","tcbStatus":"UpToDate"}]},{"id":"TDX_01","mrsigner":"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","attributes":"0000000000000000","attributesMask":"FFFFFFFFFFFFFFFF","tcbLevels":[{"tcb":{"isvsvn":0},"tcbDate":"2022-11-09T00:00:00Z","tcbStatus":"UpToDate"}]}]
```

**Comment by jyao1** [comment]
We should add it to the list.

If MIG_PROTOCOL can be negotiated, then migration can be supported.
If MIG_PROTOCOL cannot be negotiated, then migtd needs to report failure with error message (MIG_PROTOCOL failure)

**Comment by gaojiaqi7** [comment]
@jyao1 , as in [https://sbx.api.trustedservices.intel.com/tdx/certification/v4/tcb?fmspc=20806F000000](https://sbx.api.trustedservices.intel.com/tdx/certification/v4/tcb?fmspc=20806F000000) the `tdxModuleIdentities` is correspond to the `fmspc`, I think it will be better to move it to the `Platform` policy, any comments?
