### ISSUE TITLE
The use of `unwrap_or(0)` in now() may hide errors in getting the system time

### ISSUE THREAD

**Issue by liuw1** [intel/MigTD#209]
```
pub fn now() -> SystemTime {
    SystemTime(sys_time::get_sys_time().unwrap_or(0) as u64)
}
```

**Comment by gaojiaqi7** [comment]
The real time is required by TLS library but it is not actually used for customized certificate verification because the time read from rtc is not trusted. The `0` value has no impact on function and security.

**Comment by liuw1** [comment]
ok
