### ISSUE TITLE
migtd default policy for SVN does not work

### ISSUE THREAD

**Issue by jyao1** [intel/MigTD#22]
https://github.com/intel/MigTD/blob/main/config/policy.json

Currently, below is using greater-or-equal.
```
            "TEE_TCB_SVN.SEAM":{
                "operation":"greater-or-equal",
                "reference":"self"
            },
```

The meaning is: the data in **destination** is greater-or-equal to the data in **source**.
But the current flow is the data in **peer** is greater-or-equal to the data in **local**. (https://github.com/intel/MigTD/blob/main/src/policy/src/config.rs#L132)

**Comment by gaojiaqi7** [comment]
if the `reference` is a numerical value and `operation` is `greater-or-equal`, it means `peer >= value` or `dst >= value`?
