### ISSUE TITLE
with_capacity(): The use of `unsafe` block to set the length of the buffer without initializing it can lead to undefined behavior

### ISSUE THREAD

**Issue by liuw1** [intel/MigTD#232]
sha: https://github.com/intel/MigTD/commit/436786bfe6e2cf14cffaa4015d1ede18f290a6ab
File: src/std-support/rust-std-stub/src/io/buffered/bufreader.rs
Function: BufReader<R>::with_capacity
Description:
The use of `unsafe` block to set the length of the buffer without initializing it can lead to undefined behavior.
```rust
95: pub fn with_capacity(capacity: usize, inner: R) -> BufReader<R> {
96: unsafe {
97: let mut buffer = Vec::with_capacity(capacity);
98: buffer.set_len(capacity);
99: inner.initializer().initialize(&mut buffer);
100: BufReader { inner, buf: buffer.into_boxed_slice(), pos: 0, cap: 0 }
101: }
102: }
```

**Comment by gaojiaqi7** [comment]
The `buffer` is initialized by `inner`, so this is shoud be intentional
