### ISSUE TITLE
Add FMSPC for cross platform migration

### ISSUE THREAD

**Issue by jyao1** [intel/MigTD#44]
Current default migration policy assumes the source and destination are same.
We need support cross platform migration.

Rough thought:
* Add `tcbInfo` for the platform
  * ~Add `version`~
  * Add `fmspc`
  * Add `tdxtcbcomponents` for component's `svn`
  * Add `pcesvn`
  * Add `sgxtcbcomponents` for component's `svn` - SGX is still needed.
  * ~Use `advisoryIDs` as optional choice. But it might be a long list, and keeps increasing.~
* Add `TdxModuleIdentity`
  * `TdxModuleMajorVersion`
  * `TdxModuleSVN`
* Add `QuotingEnclaveReport` as Quoting Enclave (QE) Identity
  * `MISCSELECT`
  * `Attributes`
  * `MRENCLAVE`
  * `MRSIGNER`
  * `ISVProdID`
  * `ISVSVN`

Reference: 
1) https://api.portal.trustedservices.intel.com/content/documentation.html#pcs-tcb-info-tdx-v4
2) https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/

NOTE: It could be changed in future.

**Comment by gaojiaqi7** [comment]
It brings an open to verify the policy by comparing the values of peer with `Self`. MigTD can get peer's `Platform TCB` and `QE Identity` from its quote by calling the `verify_quote_integrity` API, but how shall it get the values of its own?

Option1: Get from the `verify_quote_integrity` API but it's a bit of overhead to verify its own quote.
Option2: Remodeling the `get_quote` API to output the `Platform TCB` and `QE Identity` together with the quote.
Option3: MigTD parses the quote to get the values, then the quote will no longer be transparent to MigTD.

**Comment by jyao1** [comment]
New format:
```
{
    "id": <GUID>,
    "policy": [
        {
            "fmspc": <FMSPC-value>,
            <Family-Name>: {
                <Group-Name>: {
                    <Property-Name>: {
                        "operation": <Operation-Name>,
                        "reference": <Reference-Value>
                    },
                    ...
                },
                ...
            },
        },
        ...
    ]
}

```

**Comment by gaojiaqi7** [comment]
Closed by https://github.com/intel/MigTD/pull/113
