### ISSUE TITLE
change name DMA to shared memory

### ISSUE THREAD

**Issue by jyao1** [intel/MigTD#71]

**Comment by gaojiaqi7** [comment]
Waiting for PR https://github.com/confidential-containers/td-shim/pull/616 being merged

**Comment by OuyangHang33** [comment]
Here, I'm checking this issue.

**Comment by liuw1** [comment]
There are many dma words in virtio related code, do we need to change name?

**Comment by jyao1** [comment]
yes remove DMA keyword

**Comment by gaojiaqi7** [comment]
Closed byhttps://github.com/intel/MigTD/pull/92
