### ISSUE TITLE
why use vec to hold the GHCI communciation data

### ISSUE THREAD

**Issue by jyao1** [intel/MigTD#87]
https://github.com/intel/MigTD/blob/main/src/migtd/src/migration/session.rs#L399 

Vector means the size is unpredictable.
I think it should use the static location.

**Comment by gaojiaqi7** [comment]
@jyao1 I think the size of vector used here is predictable because the size is equal to the allocated shared memory which is fixed. The return results from VMM do not affect the memory allocation.
