### ISSUE TITLE
TEE_TCB_SVN.SEAM is processed as TEE_TCB_SVN

### ISSUE THREAD

**Issue by jyao1** [intel/MigTD#96]
See: https://github.com/intel/MigTD/blob/main/src/policy/src/verify.rs#L110C8-L110C8

Just rename TEE_TCB_SVN.SEAM to TEE_TCB_SVN.

**Comment by gaojiaqi7** [comment]
Closed by https://github.com/intel/MigTD/pull/113
TEE_TCB_SVN is not longer checked by policy, it is replaced by the TCB levels represented by `tdxtcbcomponents` and `sgxtcbcomponents`
